tap "homebrew/cask-fonts"
tap "teamookla/speedtest"

brew "bat"
brew "gh"
brew "git"
brew "gradle"
brew "maven"
brew "node@18"
brew "openjdk@17"
brew "speedtest"

casl "1password-cli"
cask "android-commandlinetools"
cask "font-cascadia-code"
cask "font-cascadia-code-pl"
cask "font-cascadia-mono"
cask "font-cascadia-mono-pl"
cask "font-fira-code"

mas "Xcode", id: 497799835
